In [32]:
import pandas as pd
import numpy as np

## Read the initial dataset

In [33]:
df = pd.read_csv('DM_Dataset.csv')
df

,CommunityName,State,agepct12t21,agepct12t29,agepct16t24,agepct65up,medIncome,pctWWage,perCapInc,whitePerCap,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,ViolentCrimesPerPop,nonViolPerPop
0,Anchoragecity,AK,13.96,28.98,13.23,3.48,43946.0,90.83,19620.0,21277.0,...,1410,556.21,1880,741.62,10660,4205.13,1387,547.14,105,41.42
1,Juneaucity,AK,12.55,24.66,10.53,4.73,47924.0,89.62,19920.0,21937.0,...,18,62.3,128,443,857,2966.01,59,204.19,7,24.23
2,Fairbankscity,AK,15.45,35.12,18.14,4.70,32033.0,88.31,14665.0,16571.0,...,143,418.04,251,733.77,1460,4268.13,241,704.53,2,5.85
3,Selmacity,AL,16.96,27.15,13.50,13.84,15917.0,64.31,8844.0,14108.0,...,681,2740.99,590,2374.72,1846,7430.07,131,527.27,?,?
4,Bessemercity,AL,14.37,25.80,12.78,15.76,16331.0,66.27,8433.0,11798.0,...,651,2029.43,941,2933.47,1689,5265.29,442,1377.89,38,118.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,Sheridancity,WY,13.69,22.59,10.50,14.95,23819.0,72.14,12294.0,12466.0,...,14,93.82,62,415.49,462,3096.1,32,214.45,4,26.81
2212,Laramiecity,WY,24.78,43.68,30.33,6.70,19642.0,85.94,11652.0,11937.0,...,66,240.43,90,327.86,828,3016.28,38,138.43,7,25.5
2213,Cheyennecity,WY,13.58,26.20,12.17,10.85,28117.0,79.89,13351.0,13873.0,...,69,127.66,258,477.33,2224,4114.63,76,140.61,12,22.2
2214,Evanstoncity,WY,15.92,27.36,10.81,5.40,31193.0,86.03,12623.0,12810.0,...,24,198.48,90,744.29,496,4101.89,26,215.02,0,0
2215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,719015,832366.14,1683856,2285947.61,4728436,7461029.88,1142924,NaN,NaN,NaN

## Clean the dataset

**Step 1:** Change all columns to numerical type

In [34]:
df2 = df.copy()

In [35]:
for cols in df2.columns:
    df2[cols] = df2[cols].apply(pd.to_numeric, errors='coerce')

In [36]:
df2['State'] = df['State']

**Step 2:** Replace '?' values with the mean values of their respective states and drop np.NaN values

In [37]:
df2 = df2.drop(2215)

In [38]:
df_ViolentCrimesPerPop = df2[df2['ViolentCrimesPerPop'].notna()].copy()
df_otherPerCap = df2[df2['otherPerCap'].notna()].copy()
df_rapes = df2[df2['rapes'].notna()].copy()
df_rapesPerPop = df2[df2['rapesPerPop'].notna()].copy()
df_assaults = df2[df2['assaults'].notna()].copy()
df_assaultPerPop = df2[df2['assaultPerPop'].notna()].copy()
df_burglaries = df2[df2['burglaries'].notna()].copy()
df_burglPerPop = df2[df2['burglPerPop'].notna()].copy()
df_larcenies = df2[df2['larcenies'].notna()].copy()
df_larcPerPop = df2[df2['larcPerPop'].notna()].copy()
df_autoTheft = df2[df2['autoTheft'].notna()].copy()
df_autoTheftPerPop = df2[df2['autoTheftPerPop'].notna()].copy()
df_arsons = df2[df2['arsons'].notna()].copy()
df_arsonsPerPop = df2[df2['arsonsPerPop'].notna()].copy()
df_nonViolPerPop = df2[df2['nonViolPerPop'].notna()].copy()

In [39]:
#ViolentCrimesPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,48]):
        state = row['State']
        try:
            state_mean = df_ViolentCrimesPerPop.groupby('State').get_group(state)['ViolentCrimesPerPop'].mean()
        except KeyError:
            state_mean = df_ViolentCrimesPerPop['ViolentCrimesPerPop'].mean()
        df2.iloc[index,48] = state_mean

#otherPerCap
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,13]):
        state = row['State']
        try:
            otherPerCap_mean = df_otherPerCap.groupby('State').get_group(state)['otherPerCap'].mean()
        except KeyError:
            otherPerCap_mean = df_otherPerCap['otherPerCap'].mean()
        df2.iloc[index,13] = otherPerCap_mean

#rapes        
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,36]):
        state = row['State']
        try:
            rapes_mean = df_rapes.groupby('State').get_group(state)['rapes'].mean()
        except KeyError:
            rapes_mean = df_rapes['rapes'].mean()
        df2.iloc[index,36] = rapes_mean

#rapesPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,37]):
        state = row['State']
        try:
            rapesPerPop_mean = df_rapesPerPop.groupby('State').get_group(state)['rapesPerPop'].mean()
        except KeyError:
            rapesPerPop_mean = df_rapesPerPop['rapesPerPop'].mean()
        df2.iloc[index,37] = rapesPerPop_mean

#assaults
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,38]):
        state = row['State']
        try:
            assaults_mean = df_assaults.groupby('State').get_group(state)['assaults'].mean()
        except KeyError:
            assaults_mean = df_assaults['assaults'].mean()
        df2.iloc[index,38] = assaults_mean
        

#assaultPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,39]):
        state = row['State']
        try:
            assaultPerPop_mean = df_assaultPerPop.groupby('State').get_group(state)['assaultPerPop'].mean()
        except KeyError:
            assaultPerPop_mean = df_assaultPerPop['assaultPerPop'].mean()
        df2.iloc[index,39] = assaultPerPop_mean

#burglaries
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,40]):
        state = row['State']
        try:
            burglaries_mean = df_burglaries.groupby('State').get_group(state)['burglaries'].mean()
        except KeyError:
            burglaries_mean = df_burglaries['burglaries'].mean()
        df2.iloc[index,40] = burglaries_mean

#
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,41]):
        state = row['State']
        try:
            burglPerPop_mean = df_burglPerPop.groupby('State').get_group(state)['burglPerPop'].mean()
        except KeyError:
            burglPerPop_mean = df_burglPerPop['burglPerPop'].mean()
        df2.iloc[index,41] = burglPerPop_mean

# larcenies
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,42]):
        state = row['State']
        try:
            state_mean = df_larcenies.groupby('State').get_group(state)['larcenies'].mean()
        except KeyError:
            state_mean = df_larcenies['larcenies'].mean()
        df2.iloc[index,42] = state_mean
        
# larcPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,43]):
        state = row['State']
        try:
            state_mean = df_larcPerPop.groupby('State').get_group(state)['larcPerPop'].mean()
        except KeyError:
            state_mean = df_larcPerPop['larcPerPop'].mean()
        df2.iloc[index,43] = state_mean
        
# autoTheft
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,44]):
        state = row['State']
        try:
            state_mean = df_autoTheft.groupby('State').get_group(state)['autoTheft'].mean()
        except KeyError:
            state_mean = df_autoTheft['autoTheft'].mean()
        df2.iloc[index,44] = state_mean
        
# autoTheftPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,45]):
        state = row['State']
        try:
            state_mean = df_autoTheft.groupby('State').get_group(state)['autoTheft'].mean()
        except KeyError:
            state_mean = df_autoTheft['autoTheft'].mean()
        df2.iloc[index,45] = state_mean

# arsons
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,46]):
        state = row['State']
        try:
            state_mean = df_arsons.groupby('State').get_group(state)['arsons'].mean()
        except KeyError:
            state_mean = df_arsons['arsons'].mean()
        df2.iloc[index,46] = state_mean

# arsonsPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,47]):
        state = row['State']
        try:
            state_mean = df_arsonsPerPop.groupby('State').get_group(state)['arsonsPerPop'].mean()
        except KeyError:
            state_mean = df_arsonsPerPop['arsonsPerPop'].mean()
        df2.iloc[index,47] = state_mean

# nonViolPerPop
for index, row in df2.iterrows():
    if pd.isna(df2.iloc[index,49]):
        state = row['State']
        try:
            state_mean = df_nonViolPerPop.groupby('State').get_group(state)['nonViolPerPop'].mean()
        except KeyError:
            state_mean = df_nonViolPerPop['nonViolPerPop'].mean()
        df2.iloc[index,49] = state_mean

In [40]:
df2.iloc[:,1:].to_csv('cleaned_dataset.csv', index = False)